development:
  adapter: postgresql
  encoding: unicode
  database: cagematch_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: cagematch_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: cagematch_production
  pool: 5
